#define MANDATE_BIT 1
#define MINIMUM_BIT 2
#define MAXIMUM_BIT 4
#define MANDATE_APPLIED_BIT 8
#define MINIMUM_APPLIED_BIT 16
#define MAXIMUM_APPLIED_BIT 32
#define RESERVED_BITS ( MANDATE_BIT & MINIMUM_BIT & MAXIMUM_BIT & MANDATE_APPLIED_BIT & MINIMUM_APPLIED_BIT & MAXIMUM_APPLIED_BIT )